/**
 * AgroScan AI - Diagnostic Report Model (OOP Domain Layer).
 *
 * Encapsulates the phytosanitary report generated by Gemini 2.5 Flash,
 * providing rich utility methods for UI presentation, severity assessment,
 * and treatment categorization.
 */

import { CropType, PathogenType, RawDiagnosticResponse, SeverityLevel } from '../types';

export class DiagnosticReport {
  public readonly id: string;
  public readonly cropType: CropType;
  public readonly plotIdentifier: string;
  public readonly pathogenType: PathogenType;
  public readonly severityLevel: SeverityLevel;
  public readonly diseaseName: string;
  public readonly scientificName: string | null;
  public readonly confidenceScore: number;
  public readonly symptoms: string[];
  public readonly diagnosisSummary: string;
  public readonly organicTreatment: string[];
  public readonly chemicalTreatment: string[];
  public readonly preventiveMeasures: string[];
  public readonly createdAt: Date;
  public readonly previewImageUrl?: string;

  constructor(params: {
    id: string;
    cropType: CropType;
    plotIdentifier: string;
    pathogenType: PathogenType;
    severityLevel: SeverityLevel;
    diseaseName: string;
    scientificName?: string | null;
    confidenceScore: number;
    symptoms: string[];
    diagnosisSummary: string;
    organicTreatment: string[];
    chemicalTreatment: string[];
    preventiveMeasures: string[];
    createdAt: Date | string;
    previewImageUrl?: string;
  }) {
    this.id = params.id;
    this.cropType = params.cropType;
    this.plotIdentifier = params.plotIdentifier;
    this.pathogenType = params.pathogenType;
    this.severityLevel = params.severityLevel;
    this.diseaseName = params.diseaseName;
    this.scientificName = params.scientificName || null;
    this.confidenceScore = params.confidenceScore;
    this.symptoms = params.symptoms || [];
    this.diagnosisSummary = params.diagnosisSummary;
    this.organicTreatment = params.organicTreatment || [];
    this.chemicalTreatment = params.chemicalTreatment || [];
    this.preventiveMeasures = params.preventiveMeasures || [];
    this.createdAt = typeof params.createdAt === 'string' ? new Date(params.createdAt) : params.createdAt;
    this.previewImageUrl = params.previewImageUrl;
  }

  /**
   * Factory method to instantiate a DiagnosticReport from raw API JSON.
   */
  public static fromJSON(raw: RawDiagnosticResponse, previewImageUrl?: string): DiagnosticReport {
    return new DiagnosticReport({
      id: raw.id,
      cropType: raw.crop_type,
      plotIdentifier: raw.plot_identifier,
      pathogenType: raw.pathogen_type,
      severityLevel: raw.severity_level,
      diseaseName: raw.disease_name,
      scientificName: raw.scientific_name,
      confidenceScore: raw.confidence_score,
      symptoms: raw.symptoms,
      diagnosisSummary: raw.diagnosis_summary,
      organicTreatment: raw.organic_treatment,
      chemicalTreatment: raw.chemical_treatment,
      preventiveMeasures: raw.preventive_measures,
      createdAt: raw.created_at,
      previewImageUrl: previewImageUrl || raw.image_url,
    });
  }

  /**
   * Serializes this entity into a JSON representation for storage or transmission.
   */
  public toJSON(): RawDiagnosticResponse {
    return {
      id: this.id,
      crop_type: this.cropType,
      plot_identifier: this.plotIdentifier,
      pathogen_type: this.pathogenType,
      severity_level: this.severityLevel,
      disease_name: this.diseaseName,
      scientific_name: this.scientificName,
      confidence_score: this.confidenceScore,
      symptoms: this.symptoms,
      diagnosis_summary: this.diagnosisSummary,
      organic_treatment: this.organicTreatment,
      chemical_treatment: this.chemicalTreatment,
      preventive_measures: this.preventiveMeasures,
      created_at: this.createdAt.toISOString(),
      image_url: this.previewImageUrl,
    };
  }

  /**
   * Returns true if the diagnosis indicates immediate quarantine or chemical intervention.
   */
  public isUrgent(): boolean {
    return this.severityLevel === 'CRITICAL' || (this.severityLevel === 'MODERATE' && this.confidenceScore >= 0.9);
  }

  /**
   * Returns true if the foliage is evaluated healthy.
   */
  public isHealthy(): boolean {
    return this.pathogenType === 'HEALTHY';
  }

  /**
   * Formatted percentage confidence string.
   */
  public formattedConfidence(): string {
    return `${(this.confidenceScore * 100).toFixed(1)}%`;
  }

  /**
   * Formatted human-readable date.
   */
  public formattedDate(): string {
    return this.createdAt.toLocaleString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  }

  /**
   * Returns styling classes corresponding to severity grading.
   */
  public getSeverityStyles(): {
    badge: string;
    border: string;
    text: string;
    bgGlow: string;
    progressBar: string;
  } {
    switch (this.severityLevel) {
      case 'CRITICAL':
        return {
          badge: 'bg-rose-500/20 text-rose-400 border border-rose-500/30',
          border: 'border-rose-500/40',
          text: 'text-rose-400',
          bgGlow: 'bg-rose-500/10 shadow-[0_0_30px_rgba(244,63,94,0.15)]',
          progressBar: 'bg-gradient-to-r from-amber-500 to-rose-500',
        };
      case 'MODERATE':
        return {
          badge: 'bg-amber-500/20 text-amber-300 border border-amber-500/30',
          border: 'border-amber-500/40',
          text: 'text-amber-400',
          bgGlow: 'bg-amber-500/10 shadow-[0_0_30px_rgba(245,158,11,0.15)]',
          progressBar: 'bg-gradient-to-r from-emerald-500 to-amber-500',
        };
      case 'LOW':
      default:
        return {
          badge: 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30',
          border: 'border-emerald-500/40',
          text: 'text-emerald-400',
          bgGlow: 'bg-emerald-500/10 shadow-[0_0_30px_rgba(16,185,129,0.15)]',
          progressBar: 'bg-gradient-to-r from-teal-500 to-emerald-400',
        };
    }
  }

  /**
   * Returns pathogen category styling.
   */
  public getPathogenBadge(): { label: string; badgeClass: string } {
    switch (this.pathogenType) {
      case 'FUNGUS':
        return { label: 'FUNGAL INFECTION', badgeClass: 'bg-purple-500/20 text-purple-300 border-purple-500/30' };
      case 'BACTERIA':
        return { label: 'BACTERIAL INFECTION', badgeClass: 'bg-blue-500/20 text-blue-300 border-blue-500/30' };
      case 'VIRUS':
        return { label: 'VIRAL DISEASE', badgeClass: 'bg-red-500/20 text-red-300 border-red-500/30' };
      case 'PEST':
        return { label: 'ENTOMOLOGICAL PEST', badgeClass: 'bg-orange-500/20 text-orange-300 border-orange-500/30' };
      case 'HEALTHY':
      default:
        return { label: 'HEALTHY CANOPY', badgeClass: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30' };
    }
  }

  /**
   * Crop emoji icon representation.
   */
  public getCropIcon(): string {
    switch (this.cropType) {
      case 'Potato':
        return '🥔';
      case 'Coffee':
        return '☕';
      case 'Corn':
        return '🌽';
      case 'Tomato':
        return '🍅';
      default:
        return '🌱';
    }
  }

  /**
   * Concise text snippet for drawer cards.
   */
  public getSummarySnippet(maxLength: number = 100): string {
    if (this.diagnosisSummary.length <= maxLength) {
      return this.diagnosisSummary;
    }
    return `${this.diagnosisSummary.substring(0, maxLength).trim()}...`;
  }
}
