"""
Pydantic schemas and enums for AgroScan AI.
Defines data structures for crop diagnostics, severity classification,
and structured outputs from Google Gemini 2.5 Flash.
"""

from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field


class CropType(str, Enum):
    """
    Supported Andean crops grown predominantly in Nariño, Colombia.
    """
    POTATO = "Potato"
    COFFEE = "Coffee"
    CORN = "Corn"
    TOMATO = "Tomato"


class PathogenType(str, Enum):
    """
    Phytopathological pathogen classification categories.
    """
    FUNGUS = "FUNGUS"
    BACTERIA = "BACTERIA"
    VIRUS = "VIRUS"
    PEST = "PEST"
    HEALTHY = "HEALTHY"


class SeverityLevel(str, Enum):
    """
    Agronomic infestation or infection severity grading.
    """
    LOW = "LOW"
    MODERATE = "MODERATE"
    CRITICAL = "CRITICAL"


class TreatmentComparison(BaseModel):
    """
    Comparative treatment pathways for sustainable farm management.
    """
    organic: List[str] = Field(
        default_factory=list,
        description="Organic, biological, and eco-friendly solutions (e.g. bio-inputs, antagonistic fungi, botanical extracts)"
    )
    chemical: List[str] = Field(
        default_factory=list,
        description="Conventional chemical treatments with active ingredients, dosage rates, and application intervals"
    )


class DiagnosticResponse(BaseModel):
    """
    Full phytosanitary diagnostic report schema generated by Gemini 2.5 Flash.
    """
    id: str = Field(
        ...,
        description="Unique identifier for the diagnostic session (UUID string)"
    )
    crop_type: CropType = Field(
        ...,
        description="Type of Andean crop analyzed"
    )
    plot_identifier: str = Field(
        ...,
        description="Farmer's plot or lot identifier (e.g., 'Plot A - Upper Terrace', 'Lot 3')"
    )
    pathogen_type: PathogenType = Field(
        ...,
        description="Categorical pathogen classification"
    )
    severity_level: SeverityLevel = Field(
        ...,
        description="Agronomic severity level assessed from visual manifestations"
    )
    disease_name: str = Field(
        ...,
        description="Common commercial name of the detected illness or 'Healthy Foliage / Normal Growth'"
    )
    scientific_name: Optional[str] = Field(
        default=None,
        description="Taxonomic binomial scientific name of the causal agent (e.g., 'Phytophthora infestans')"
    )
    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Diagnostic confidence probability score between 0.00 and 1.00"
    )
    symptoms: List[str] = Field(
        default_factory=list,
        description="Observable phenotypic symptoms (chlorosis, necrotic spots, wilting, pustules, leaf curling)"
    )
    diagnosis_summary: str = Field(
        ...,
        description="Technical and agronomic summary explaining etiology and stage of the disease"
    )
    organic_treatment: List[str] = Field(
        default_factory=list,
        description="List of organic/biological recommendations with preparation instructions"
    )
    chemical_treatment: List[str] = Field(
        default_factory=list,
        description="List of chemical interventions specifying active ingredients and safety warnings"
    )
    preventive_measures: List[str] = Field(
        default_factory=list,
        description="Agronomic cultural management steps (sanitation, drainage, crop rotation, solarization)"
    )
    created_at: str = Field(
        ...,
        description="ISO 8601 UTC timestamp of diagnostic completion"
    )


class DiagnosticListResponse(BaseModel):
    """
    Response schema for past diagnostic queries.
    """
    total: int
    items: List[DiagnosticResponse]


class HealthCheckResponse(BaseModel):
    """
    System status and Gemini API connectivity health check response.
    """
    status: str
    service: str
    version: str
    gemini_configured: bool
    model: str
