"""
Pydantic schemas and enums for AgroScan AI.
Defines data structures for crop diagnostics, severity classification,
and structured outputs from Google Gemini 2.5 Flash.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field


class CropType(str, Enum):
    """
    Supported Andean crops grown predominantly in Nariño, Colombia.
    """
    POTATO = "Potato"
    COFFEE = "Coffee"
    CORN = "Corn"
    TOMATO = "Tomato"


class PathogenType(str, Enum):
    """
    Phytopathological pathogen classification categories.
    """
    FUNGUS = "FUNGUS"
    BACTERIA = "BACTERIA"
    VIRUS = "VIRUS"
    PEST = "PEST"
    HEALTHY = "HEALTHY"


class SeverityLevel(str, Enum):
    """
    Agronomic infestation or infection severity grading.
    """
    LOW = "LOW"
    MODERATE = "MODERATE"
    CRITICAL = "CRITICAL"


class TreatmentComparison(BaseModel):
    """
    Comparative treatment pathways for sustainable farm management.
    """
    organic: List[str] = Field(
        default_factory=list,
        description="Organic, biological, and eco-friendly solutions (e.g. bio-inputs, antagonistic fungi, botanical extracts)"
    )
    chemical: List[str] = Field(
        default_factory=list,
        description="Conventional chemical treatments with active ingredients, dosage rates, and application intervals"
    )


class DiagnosticResponse(BaseModel):
    """
    Full phytosanitary diagnostic report schema generated by Gemini 2.5 Flash
    and persisted in MongoDB Atlas.
    """
    id: str = Field(
        ...,
        description="Unique identifier for the diagnostic session (UUID string)"
    )
    user_id: Optional[str] = Field(
        default=None,
        description="Farmer account ID associated with this diagnostic record"
    )
    crop_type: CropType = Field(
        ...,
        description="Type of Andean crop analyzed"
    )
    plot_identifier: str = Field(
        ...,
        description="Farmer's plot or lot identifier (e.g., 'Plot A - Upper Terrace', 'Lot 3')"
    )
    pathogen_type: PathogenType = Field(
        ...,
        description="Categorical pathogen classification"
    )
    severity_level: SeverityLevel = Field(
        ...,
        description="Agronomic severity level assessed from visual manifestations"
    )
    disease_name: str = Field(
        ...,
        description="Common commercial name of the detected illness or 'Healthy Foliage / Normal Growth'"
    )
    scientific_name: Optional[str] = Field(
        default=None,
        description="Taxonomic binomial scientific name of the causal agent (e.g., 'Phytophthora infestans')"
    )
    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Diagnostic confidence probability score between 0.00 and 1.00"
    )
    symptoms: List[str] = Field(
        default_factory=list,
        description="Observable phenotypic symptoms (chlorosis, necrotic spots, wilting, pustules, leaf curling)"
    )
    diagnosis_summary: str = Field(
        ...,
        description="Technical and agronomic summary explaining etiology and stage of the disease"
    )
    organic_treatment: List[str] = Field(
        default_factory=list,
        description="List of organic/biological recommendations with preparation instructions"
    )
    chemical_treatment: List[str] = Field(
        default_factory=list,
        description="List of chemical interventions specifying active ingredients and safety warnings"
    )
    preventive_measures: List[str] = Field(
        default_factory=list,
        description="Agronomic cultural management steps (sanitation, drainage, crop rotation, solarization)"
    )
    created_at: str = Field(
        ...,
        description="ISO 8601 UTC timestamp of diagnostic completion"
    )


class DiagnosticListResponse(BaseModel):
    """
    Response schema for past diagnostic queries.
    """
    total: int
    items: List[DiagnosticResponse]


class HealthCheckResponse(BaseModel):
    """
    System status and Gemini API connectivity health check response.
    """
    status: str
    service: str
    version: str
    gemini_configured: bool
    mongodb_connected: bool = False
    model: str


class FarmerRole(str, Enum):
    """
    Agricultural practitioner role classification.
    """
    SMALLHOLDER = "Smallholder Farmer"
    AGRONOMIST = "Agronomist / Extensionist"
    COOP_MEMBER = "Cooperative Producer"
    RESEARCHER = "Agricultural Researcher"


class UserProfile(BaseModel):
    """
    Public profile information of an authenticated farmer or agronomist.
    """
    id: str
    email: str
    full_name: str
    farm_name: str
    municipality: str
    role: FarmerRole
    avatar_url: Optional[str] = None
    created_at: str


class UserRegisterRequest(BaseModel):
    """
    Payload for creating a new farmer user account.
    """
    email: str
    password: str
    full_name: str
    farm_name: str = "Finca La Esperanza"
    municipality: str = "Túquerres"
    role: FarmerRole = FarmerRole.SMALLHOLDER


class UserLoginRequest(BaseModel):
    """
    Payload for authenticating an existing user.
    """
    email: str
    password: str


class AuthResponse(BaseModel):
    """
    Authentication token and user profile payload.
    """
    access_token: str
    token_type: str = "bearer"
    user: UserProfile


class ChatMessage(BaseModel):
    """
    Individual conversational turn between the farmer and the agronomic assistant.
    """
    role: str = Field(
        ...,
        description="Originating speaker role ('user' | 'model')"
    )
    content: str = Field(
        ...,
        description="Text content of the message"
    )
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO 8601 UTC timestamp of message dispatch"
    )


class ChatFollowUpRequest(BaseModel):
    """
    Payload for submitting an agronomic follow-up inquiry grounded on a diagnostic report.
    """
    diagnostic_id: str = Field(
        ...,
        description="Unique ID of the parent phytosanitary diagnostic record"
    )
    message: str = Field(
        ...,
        description="Farmer's agronomic or field application question"
    )
    chat_history: Optional[List[ChatMessage]] = Field(
        default_factory=list,
        description="Preceding message turns in this consultative thread"
    )


class ChatFollowUpResponse(BaseModel):
    """
    Structured agronomic response generated by Gemini 2.5 Flash with quick-tap follow-up chips.
    """
    reply: str = Field(
        ...,
        description="Contextual, field-oriented advice provided by the extension agronomist"
    )
    suggested_followups: List[str] = Field(
        default_factory=list,
        description="2-3 brief suggested questions the farmer can quickly tap next"
    )
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO 8601 UTC timestamp of assistant reply generation"
    )

